liberty/client/urls.py
from django.conf.urls import patterns, url
from client import views

urlpatterns = patterns('',
    url(r'^index', views.index, name='index'),
    url(r'^(?P<client_id>\d+)/$',
        views.detail, name='detail'),
    url(r'^addclient', views.addclient, name='addclient'),
    url(r'^editclient/(?P<client_id>\d+)/$', views.editclient, name='editclient'),
    url(r'^addsalesprospect', views.addsalesprospect, name='addsalesprospect'),
    url(r'^salesprospectindex', views.salesprospectindex, name='salesprospectindex'),
    url(r'^salesprospectdetail/(?P<sales_prospect_id>\d+)/$',
        views.salesprospectdetails, name='salesprospectdetails'),
    url(r'^editsalesprospect/(?P<sales_prospect_id>\d+)/$',
        views.editsalesprospect, name='editsalesprospect'),
)

liberty/employee/urls.py
from django.conf.urls import patterns, url
from employee import views

urlpatterns = patterns('',
    url(r'^(?P<employee_id>\d+)/$',
        views.details, name='details'),
    url(r'index/$', views.index, name="index"),
    #url(r'addemployee/$', views.addemployee, name='addemployee'),
    url(r'title/$', views.titleform, name='titleform'),
    url(r'empform/$', views.empform, name='empform'),
    #url(r'empform1/$', views.empform1, name='empform1'),
    url(r'editemployee/(?P<employee_id>\d+)/$', views.editemployee,
        name='editemployee'),
    #r'^salesprospectdetail/(?P<sales_prospect_id>\d+)/$',
)

liberty/liberty/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import autocomplete_light
# import every app/autocomplete_light_registry.py
autocomplete_light.autodiscover()
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^employeetest/', include('employee.urls', namespace="employee")),
    url(r'^clienttest/', include('client.urls', namespace="client")),
    url(r'^site_infotest/', include('site_info.urls', namespace="site_info")),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    # Examples:
    # url(r'^$', 'liberty.views.home', name='home'),
    # url(r'^liberty/', include('liberty.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

)
urlpatterns += staticfiles_urlpatterns()

liberty/employee/models.py
#Employee models
from django.db import models
#from django import forms
from common.models import Person

class Title(models.Model):
    SALES = 'S'
    TECHNICIAN = 'T'
    OFFICE = 'O'
    MARKETING = 'M'
    CONTRACTOR = 'C'
    INTERN = 'I'
    TITLE_CHOICES = (
        (SALES, "Sales"),
        (TECHNICIAN, "Technician"),
        (OFFICE, "Office"),
        (MARKETING, "Marketing"),
        (CONTRACTOR, "Contractor"),
        (INTERN, "Intern"),
    )
    title_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=2, choices=TITLE_CHOICES)

    def __unicode__(self):
        return self.get_title_display()


class Employee(Person):
    PAY_TYPE_CHOICES = (
        ('COM', 'Commission'),
        ('HR', 'Hourly'),
        ('SAL', 'Salary'),
        ('OT', 'Other'),
    )
    employee_id = models.AutoField(primary_key=True)
    employee_number = models.IntegerField(max_length=10)
    e_title = models.ManyToManyField(Title, verbose_name="Employee Title(s)")
    address = models.ForeignKey('common.Address')
    contact_info = models.ForeignKey('common.Contact')
    hire_date = models.DateField()
    pay_type = models.CharField(max_length=3, choices=PAY_TYPE_CHOICES, default='HR')
    pay_rate = models.DecimalField("employee pay rate", max_digits=10, decimal_places=2, blank=True)
    termination_date = models.DateField(null=True, blank=True)
    termination_reason = models.CharField(max_length=300, blank=True)
    #e.e_title.add(t)
    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

    def worker_is(self):
        return (self.e_title)

liberty/employee/forms.py
from models import Employee, Title
from django.forms import ModelForm, Textarea
from bootstrap_toolkit.widgets import BootstrapDateInput


class EmployeeForm(ModelForm):
    class Meta:
        model = Employee
        # exclude foreign keys
        exclude = ('address', 'contact_info',)
        widgets = {
            'hire_date': BootstrapDateInput, 'termination_date': BootstrapDateInput,
            'termination_reason': Textarea(attrs={'cols': 160, 'rows': 10})
        }


class AddEmployeeForm(EmployeeForm):
    class Meta(EmployeeForm.Meta):
        exclude = ('address', 'contact_info', 'termination_date', 'termination_reason',)


class TitleForm(ModelForm):
    class Meta:
        model = Title

liberty/employee/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from employee.models import Employee, Title
from employee.forms import EmployeeForm, AddEmployeeForm
from common.models import Address, Contact, City
from common.forms import AddressForm, EmployeeContactForm, AddressFormPlaces, CityFormNotAuto
from helpermethods import create_employee, update_employee
from common.helpermethods import city_worker, create_address, create_employee_contact, handle_auto_city, update_address, update_employee_contact, validation_helper, form_generator, dict_generator


def index(request):
    """
    List of all Employees.
    @param request: request.
    @return: rendered view with all Employees.
    """
    all_employees_list = Employee.objects.order_by('last_name')
    context = {'all_employees_list': all_employees_list}
    return render(request, 'employee/index.html', context)


def details(request, employee_id):
    """
    Detailed view of Employee.
    @param request: request.
    @param employee_id: Employee pk.
    @return: rendered view with Employee details.
    """
    employee_detail = Employee.objects.get(pk=employee_id)
    address_detail = Address.objects.get(pk=employee_detail.address_id)
    contact_detail = Contact.objects.get(pk=employee_detail.contact_info_id)
    title_details = employee_detail.e_title.all()
    context = {
        'employee_detail': employee_detail, 'address_detail': address_detail,
        'contact_detail': contact_detail, 'title_details': title_details
    }
    return render(request, 'employee/detail.html', context)


def empform(request):
    """
    Creates a new Employee.
    @param request: request.
    @return: redirect to index or form with validation errors.
    """
    form_list = form_generator(4)
    if request.method == 'POST':  # If form has been submitted...
        form_list[0] = AddEmployeeForm(request.POST)
        form_list[1] = CityFormNotAuto(request.POST)
        form_list[2] = AddressFormPlaces(request.POST)
        form_list[3] = EmployeeContactForm(request.POST)
        #form_list = [form0, form1, form2, form3]
        validation = validation_helper(form_list)

        if validation:
            #city
            city_f = request.POST.get('city_name')
            c = city_worker(request, city_f)
            # address
            a = create_address(request, c)
            # contact
            con = create_employee_contact(request)
            # employee
            e = create_employee(request, a, con)

            return HttpResponseRedirect('/employeetest/index/')
    else:
        # unbound forms
        form_list[0] = AddEmployeeForm()
        form_list[1] = CityFormNotAuto()
        form_list[2] = AddressFormPlaces()
        form_list[3] = EmployeeContactForm()
    form_dict = dict_generator(form_list)

    return render(request, 'title.html', form_dict)


def editemployee(request, employee_id):
    # bound form
    """
    Edits an Employee object
    @param request: request.
    @param employee_id: Employee pk.
    @return: redirect or form with validation errors.
    """
    form_list = form_generator(4)
    employee = Employee.objects.get(pk=employee_id)
    address = Address.objects.get(pk=employee.address_id)
    contact = Contact.objects.get(pk=employee.contact_info_id)
    city = City.objects.get(pk=address.city_id)
    title_details = employee.e_title.all()
    # create data dictionaries
    employee_dict = {'first_name': employee.first_name, 'last_name': employee.last_name,
                'employee_number': employee.employee_number, 'e_title': title_details,
                'hire_date': employee.hire_date, 'pay_type': employee.pay_type,
                'pay_rate': employee.pay_rate, 'termination_date': employee.termination_date,
                'termination_reason': employee.termination_reason
    }
    address_dict = {'address': address.address, 'address2': address.address2,
                    'city': address.city_id, 'state': address.state, 'zip_code': address.zip_code
    }
    contact_dict = {'phone': contact.phone, 'cell': contact.cell, 'email': contact.email}
    city_dict = {'city_name': city.city_name}
    # form submission
    if request.method == 'POST':
        form_list[0] = EmployeeForm(request.POST)
        form_list[1] = CityFormNotAuto(request.POST)
        form_list[2] = AddressFormPlaces(request.POST)
        form_list[3] = EmployeeContactForm(request.POST)
        validation = validation_helper(form_list)

        if validation:
                cit = city_worker(request, request.POST.get('city_name'))
                address = update_address(request, address, cit)
                con = update_employee_contact(request, contact)
                employee = update_employee(request, employee, address, con)
                return HttpResponseRedirect('/employeetest/index/')
    else:
        # redisplay bound form
        form_list[0] = EmployeeForm(employee_dict)
        form_list[2] = AddressFormPlaces(address_dict)
        form_list[1] = CityFormNotAuto(city_dict)
        form_list[3] = EmployeeContactForm(contact_dict)
    form_dict = dict_generator(form_list)
    return render(request, 'employee/editemployee.html', form_dict)


def titleform(request):
    """
    Form to create employee.
    @param request: request.
    @return: rendered view or new employee and redirect.
    """
    print("titleform view called")
    if request.method == 'POST':
        print("POST called")
        form = AddEmployeeForm()
        form1 = AddressForm(request.POST)
        form2 = EmployeeContactForm(request.POST)
    else:
        print('ELSE CALLED!!!')
        form = AddEmployeeForm()
        form1 = AddressForm()
        form2 = EmployeeContactForm()
    return render(request, 'title.html', {'form': form, 'form1': form1, 'form2': form2})

liberty/employee/templates/employee/addemployee.html
{% extends 'base.html' %}

{% load bootstrap_toolkit %}

{% block content %}
{{ form|as_bootstrap }}

<fieldset>
<!-- Form Name -->
<legend>Employee Information</legend>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="firstname">First Name</label>
  <div class="controls">
    <input id="firstname" name="firstname" type="text" placeholder="first name" class="input-large" required="">

  </div>
</div>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="lastname">Last Name</label>
  <div class="controls">
    <input id="lastname" name="lastname" type="text" placeholder="last name" class="input-large" required="">

  </div>
</div>

<!-- Select Multiple -->
<div class="control-group">
  <label class="control-label" for="title">Titles</label>
  <div class="controls">
    <select id="title" name="title" class="input-medium" multiple="multiple">
      <option>Officer</option>
      <option>Technician</option>
      <option>Sales</option>
    </select>
  </div>
</div>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="hiredate">Hire Date</label>
  <div class="input-append">
            <input data-bootstrap-widget="datepicker" data-date-format="yyyy-mm-dd" data-date-language="en-US" id="id_date" name="date" type="text" /><span class="add-on"><i class="icon-calendar"></i></span>
        </div>
</div>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="paytype">Pay Type</label>
  <div class="controls">
    <input id="paytype" name="paytype" type="text" placeholder="pay type" class="input-medium" required="">

  </div>
</div>

<!-- Select Basic -->
<div class="control-group">
  <label class="control-label" for="payrate">Pay Rate</label>
  <div class="controls">
    <select id="payrate" name="payrate" class="input-small">
      <option>$10.00</option>
      <option>$20.00</option>
    </select>
  </div>
</div>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="terminationdate">Termination Date</label>
  <div class="controls">
    <input data-bootstrap-widget="datepicker" data-date-format="yyyy-mm-dd" data-date-language="en-US"
    id="terminationdate" name="terminationdate" type="text" placeholder="termination date" class="input-medium">
      <span class="add-on"><i class="icon-calendar"></i></span>
        </div>
  </div>


<!-- Textarea -->
<div class="control-group">
  <label class="control-label" for="terminationreason">Termination Reason</label>
  <div class="controls">
    <textarea id="terminationreason" name="terminationreason">Termination Reason</textarea>
  </div>
</div>

</fieldset>


{% endblock %}

liberty/employee/templates/employee/detail.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}

{% block content %}
{% if employee_detail %}
    <a href="{% url 'employee:editemployee' employee_detail.employee_id %}">
        Edit Employee Information
    </a>
    <ul>
        <li>
            Employee Info
        </li>
        <li>
                {{employee_detail.employee_number}}
        </li>
        <li>
                {{employee_detail.first_name}}
                {{employee_detail.last_name}}
        </li>
        <li>
                {{employee_detail.hire_date}}
        </li>
        {% if title_details %}
        <li>
            Employee has {{ title_details|length }} title{{ title_details|pluralize }}.
        </li>
        {% for t in title_details %}
        <li>
            {{ t.get_title_display }}
        </li>
        {% endfor %}
        {% else %}
        <li>
            No titles on file
        </li>
        {% endif %}
        <li>
            Employee Address:
        </li>
        {% if address_detail %}
        <li>
            {{ address_detail }}
        </li>
        {% else %}
        <li>
            No address info.
        </li>
        {% endif %}
        <li>
            Employee Contact:
        </li>
        {% if contact_detail %}
        <li>
            {{ contact_detail }}
        </li>
        {% else %}
        <li>
            No contact information
        </li>
        {% endif %}
    </ul>
{% else %}
        <p>No employees are available.</p>
{% endif %}

{% endblock %}

liberty/employee/templates/employee/editemployee.html
{% extends 'base.html' %}
{% block body_block %}
    <body onload="initialize()">
{% endblock %}
{% load bootstrap_toolkit %}

# Using a filter

{% block content %}
<p>Update employee information.</p>
<form action="" method="post">{% csrf_token %}

    <p>Employee Information</p>
    {{ form0|as_bootstrap }}

    <p>Address Information</p>
    <div id="locationField">
        <input id="autocomplete" placeholder="Enter your address"
        onFocus="geolocate()" type="text"></input>
    </div>
    {{ form2|as_bootstrap }}
    {{ form1|as_bootstrap }}

    <p>Contact Information</p>
    {{ form3|as_bootstrap }}

<br />
<input type="submit" value="Submit" class="btn btn-primary" />
</form>

{% endblock %}

liberty/employee/templates/employee/empform.html
{% extends 'base.html' %}

{% load bootstrap_toolkit %}
<form action="" method="post">{% csrf_token %}
{% block content %}
    <p>Employee Information</p>
    {{ form|as_bootstrap }}

    <p>Address Information</p>
    {{ form1|as_bootstrap }}

    <p>Contact Information</p>
    {{ form2|as_bootstrap }}

    {{ form3|as_bootstrap }}
<br />
<input type="submit" value="Submit" class="btn btn-primary" />
</form>
{% endblock %}

liberty/employee/templates/employee/employee.html
<form class="form-horizontal">
<fieldset>

<!-- Form Name -->
<legend>Employee Information</legend>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="firstname">First Name</label>
  <div class="controls">
    <input id="firstname" name="firstname" type="text" placeholder="first name" class="input-large" required="">

  </div>
</div>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="lastname">Last Name</label>
  <div class="controls">
    <input id="lastname" name="lastname" type="text" placeholder="last name" class="input-large" required="">

  </div>
</div>

<!-- Select Multiple -->
<div class="control-group">
  <label class="control-label" for="title">Titles</label>
  <div class="controls">
    <select id="title" name="title" class="input-medium" multiple="multiple">
      <option>Officer</option>
      <option>Technician</option>
      <option>Sales</option>
    </select>
  </div>
</div>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="hiredate">Hire Date</label>
  <div class="controls">
    <input id="hiredate" name="hiredate" type="text" placeholder="hire date" class="input-medium" required="">

  </div>
</div>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="paytype">Pay Type</label>
  <div class="controls">
    <input id="paytype" name="paytype" type="text" placeholder="pay type" class="input-medium" required="">

  </div>
</div>

<!-- Select Basic -->
<div class="control-group">
  <label class="control-label" for="payrate">Pay Rate</label>
  <div class="controls">
    <select id="payrate" name="payrate" class="input-small">
      <option>$10.00</option>
      <option>$20.00</option>
    </select>
  </div>
</div>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="terminationdate">Termination Date</label>
  <div class="controls">
    <input id="terminationdate" name="terminationdate" type="text" placeholder="termination date" class="input-medium">

  </div>
</div>

<!-- Textarea -->
<div class="control-group">
  <label class="control-label" for="terminationreason">Termination Reason</label>
  <div class="controls">
    <textarea id="terminationreason" name="terminationreason">Termination Reason</textarea>
  </div>
</div>

</fieldset>
</form>

liberty/employee/templates/employee/index.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}

# Using a filter

{% block content %}
<p>Welcome to the Liberty Security Services Employee Management site.</p>
<p>Please select an option from the following choices or go back to the home page.</p>

{% if all_employees_list %}
    <ul>
        {% for e in all_employees_list %}
        <li>
                <a href="{% url 'employee:details' e.employee_id %}">
                {{e.employee_id}} {{e.first_name}} {{e.last_name}}
            </a>
        </li>
        {% endfor %}
    </ul>
{% else %}
        <p>No employees are available.</p>
{% endif %}
        {% comment %}
//<a href="/employeetest/{{ e.employee_id }}/">
    <a href="{% url 'detailed' e.employee_id %}">
        <a href="/employeetest/{{ e.employee_id }}/">
    {% endcomment %}

{% endblock %}

liberty/employee/templates/employee/indexer.html
{% if all_employees_list %}
    <ul>
        {% for e in all_employees_list %}
        <li>
                <a href="{% url 'employee:detailed' e.employee_id %}">
                {{e.first_name}} {{e.last_name}}
            </a>
        </li>
        {% endfor %}
    </ul>
{% else %}
        <p>No employees are available.</p>
{% endif %}
        {% comment %}
//<a href="/employeetest/{{ e.employee_id }}/">
    <a href="{% url 'detailed' e.employee_id %}">
        <a href="/employeetest/{{ e.employee_id }}/">
    {% endcomment %}

liberty/employee/templates/employee/search_form.html
<html>
<head>
    <title>Search</title>
</head>
<body>
     {% if error %}
        <p style="color: red;">Please submit a search term.</p>
    {% endif %}
    <form action="/employeetest/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

liberty/employee/templates/employee/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>

{% if employees %}
    <p>Found {{ employees|length }} employee{{ employees|pluralize }}.</p>
    <ul>
        {% for e in employees %}
        <li>
            <a href="{% url 'employee:detailed' e.employee_id %}">
            {{ e.first_name }} {{ e.last_name }}
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No employees matched your search criteria.</p>
{% endif %}

liberty/employee/templates/employee/test.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}

# Using a filter

<form action="/url/to/submit/" method="post">
    {% csrf_token %}
    {{ form|as_bootstrap }}
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

# Using template tags

<form action="/url/to/submit/" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form layout="vertical" %}
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

        {% block content %}

    <h1>This is a <em>{{ layout }}</em> Django formset, bootstrapped</h1>

    <p>&nbsp;</p>

    <form class="form-{{ layout }}" action="" method="post">
        {% csrf_token %}

        {% bootstrap_formset formset=formset layout=layout %}

        {% if layout == "horizontal" %}
            <p class="form-actions">
                <input type="submit" value="Submit" class="btn btn-primary">
            </p>
        {% else %}
            <input type="submit" value="Submit" class="btn btn-primary">
        {% endif %}
    </form>

    <p>Submit the form to see error messages styled into it.</p>



    <div class="well">
        <h1>Django, meet Bootstrap!</h1>
        <p>The django-bootstrap-toolkit application allows for an easy integration of Django and Bootstrap.</p>
        <p><a class="btn btn-primary" href="https://github.com/dyve/django-bootstrap-toolkit/">Check it out on GitHub &raquo;</a></p>
    </div>

    <div class="row">
        <div class="span4">
            <h2>Django</h2>

            <p>Django is the excellent Python web framework that makes a programmer's life less repetitive.</p>

            <p><a class="btn" href="http://www.djangoproject.com">View details &raquo;</a></p>
        </div>
        <div class="span4">
            <h2>Bootstrap</h2>

            <p>Bootstrap is a beautiful CSS framework with an optional JavaScript add-on.</p>

            <p><a class="btn" href="http://twitter.github.com/bootstrap/">View details &raquo;</a></p>
        </div>
        <div class="span4">
            <h2>django-bootstrap-toolkit</h2>

            <p>Is just a simple hustle to get two kinds of awesome together.</p>

            <p><a class="btn" href="https://github.com/dyve/django-bootstrap-toolkit/">View details &raquo;</a></p>
        </div>
    </div>

    <p>A big thanks to all the people that worked on Django and Bootstrap.</p>

{% endblock %}

liberty/employee/templates/employee/title.html
{% block content %}
  {{ form }}
{% endblock %}