liberty/client/urls.py
from django.conf.urls import patterns, url
from client import views

urlpatterns = patterns('',
    url(r'^index', views.index, name='index'),
    url(r'^(?P<client_id>\d+)/$',
        views.detail, name='detail'),
    url(r'^addclient', views.addclient, name='addclient'),
    url(r'^editclient/(?P<client_id>\d+)/$', views.editclient, name='editclient'),
    url(r'^addsalesprospect', views.addsalesprospect, name='addsalesprospect'),
    url(r'^salesprospectindex', views.salesprospectindex, name='salesprospectindex'),
    url(r'^salesprospectdetail/(?P<sales_prospect_id>\d+)/$',
        views.salesprospectdetails, name='salesprospectdetails'),
    url(r'^editsalesprospect/(?P<sales_prospect_id>\d+)/$',
        views.editsalesprospect, name='editsalesprospect'),
)

liberty/employee/urls.py
from django.conf.urls import patterns, url
from employee import views

urlpatterns = patterns('',
    url(r'^(?P<employee_id>\d+)/$',
        views.details, name='details'),
    url(r'index/$', views.index, name="index"),
    #url(r'addemployee/$', views.addemployee, name='addemployee'),
    url(r'title/$', views.titleform, name='titleform'),
    url(r'empform/$', views.empform, name='empform'),
    #url(r'empform1/$', views.empform1, name='empform1'),
    url(r'editemployee/(?P<employee_id>\d+)/$', views.editemployee,
        name='editemployee'),
    #r'^salesprospectdetail/(?P<sales_prospect_id>\d+)/$',
)

liberty/liberty/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import autocomplete_light
# import every app/autocomplete_light_registry.py
autocomplete_light.autodiscover()
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^employeetest/', include('employee.urls', namespace="employee")),
    url(r'^clienttest/', include('client.urls', namespace="client")),
    url(r'^site_infotest/', include('site_info.urls', namespace="site_info")),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    # Examples:
    # url(r'^$', 'liberty.views.home', name='home'),
    # url(r'^liberty/', include('liberty.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

)
urlpatterns += staticfiles_urlpatterns()

liberty/site_info/urls.py
from django.conf.urls import patterns, url
from site_info import views

urlpatterns = patterns('',
    url(r'^(?P<site_id>\d+)/$',
        views.detail, name='detail'),
    url(r'index/$', views.index, name="index"),
    url(r'addsite/$', views.addsiteinfo, name="addsiteinfo"),
)

liberty/templates/base.html
<!DOCTYPE html>
{% load bootstrap_toolkit %}
{% load url from future %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Liberty Security Services</title>
    <meta name="description" content="">
    <meta name="author" content="Taiowa Waner">
{% bootstrap_stylesheet_tag %}
{% bootstrap_stylesheet_tag "responsive" %}

    <style type="text/css">
        body {
            padding-top: 60px;
        }
    </style>
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
    <!-- Breaks dropdown menu
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    -->

    <link href="/static/datepicker/css/datepicker.css" type="text/css" media="screen" rel="stylesheet" />
    <script type="text/javascript" src="/static/datepicker/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="/static/bootstrap_toolkit/js/init_datepicker.js"></script>
    <script type="text/javascript" src="/static/js/address_autocomplete.js"><</script>
    {% include 'autocomplete_light/static.html' %}
    {% bootstrap_javascript_tag %}
    {% block extra_head %}{% endblock %}
</head>
{% block body_block %}
<body>
{% endblock %}
{% load staticfiles %}
<img src="{{ STATIC_URL }}media/website_logo_sm.png"  alt="Liberty Logo"/>
<!--<img src="{% static "media/website_logo_sm.png" %}"  alt="Liberty Logo"/>-->
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">Liberty Security Services </a>
            <ul class="nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Employee<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'employee:index' %}">Employee Home</a></li>
                        <li><a href="{% url 'employee:empform' %}">Add Employee</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Client<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'client:index' %}">Client Home</a> </li>
                        <li><a href="{% url 'client:addclient' %}">Add Client</a></li>
                        <li><a href="{% url 'client:salesprospectindex' %}">Sales Prospect Home</a></li>
                        <li><a href="{% url 'client:addsalesprospect' %}">Add Sales Prospect</a></li>
                    </ul>
                </li>
                 <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Site<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'site_info:index' %}">Site Home</a></li>
                        <li><a href="{% url 'site_info:addsiteinfo' %}">Add Site Info</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="container">

    {% bootstrap_messages %}

    {% block content %}Empty page{% endblock %}

    <p><hr></p>

    <footer class="row">
        <div class="span6">
            <p>Built using <a href="https://github.com/dyve/django-bootstrap-toolkit">django-bootstrap-toolkit</a></p>
            <p>Powered by django</p>
        </div>
        <div class="span6" style="text-align:right">
            <p>
                &copy; <a href="http://twitter.com/wanert">Taiowa Waner</a> 2013
                |
                <a href="https://raw.github.com/dyve/django-bootstrap-toolkit/master/LICENSE">license</a>
            </p>
            <p>
                Address Autocomplete <br />
                <img src="{{ STATIC_URL }}media/powered-by-google-on-white.png"  alt="Liberty Logo"/>
            </p>
        </div>
    </footer>

</div> <!-- container -->

</body>
</html>