liberty/client/urls.py
from django.conf.urls import patterns, url
from client import views

urlpatterns = patterns('',
    url(r'^index', views.index, name='index'),
    url(r'^(?P<client_id>\d+)/$',
        views.detail, name='detail'),
    url(r'^addclient', views.addclient, name='addclient'),
    url(r'^editclient/(?P<client_id>\d+)/$', views.editclient, name='editclient'),
    url(r'^addsalesprospect', views.addsalesprospect, name='addsalesprospect'),
    url(r'^salesprospectindex', views.salesprospectindex, name='salesprospectindex'),
    url(r'^salesprospectdetail/(?P<sales_prospect_id>\d+)/$',
        views.salesprospectdetails, name='salesprospectdetails'),
    url(r'^editsalesprospect/(?P<sales_prospect_id>\d+)/$',
        views.editsalesprospect, name='editsalesprospect'),
)

liberty/employee/urls.py
from django.conf.urls import patterns, url
from employee import views

urlpatterns = patterns('',
    url(r'^(?P<employee_id>\d+)/$',
        views.details, name='details'),
    url(r'index/$', views.index, name="index"),
    #url(r'addemployee/$', views.addemployee, name='addemployee'),
    url(r'title/$', views.titleform, name='titleform'),
    url(r'empform/$', views.empform, name='empform'),
    #url(r'empform1/$', views.empform1, name='empform1'),
    url(r'editemployee/(?P<employee_id>\d+)/$', views.editemployee,
        name='editemployee'),
    #r'^salesprospectdetail/(?P<sales_prospect_id>\d+)/$',
)

liberty/liberty/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import autocomplete_light
# import every app/autocomplete_light_registry.py
autocomplete_light.autodiscover()
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^employeetest/', include('employee.urls', namespace="employee")),
    url(r'^clienttest/', include('client.urls', namespace="client")),
    url(r'^site_infotest/', include('site_info.urls', namespace="site_info")),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    # Examples:
    # url(r'^$', 'liberty.views.home', name='home'),
    # url(r'^liberty/', include('liberty.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

)
urlpatterns += staticfiles_urlpatterns()

liberty/client/models.py
# Client Model
from django.db import models
from common.models import Person
from employee.models import Employee

# USE 0 == False // 1 == True!


class BusinessManager(models.Manager):
    def get_query_set(self):
        """
        Model manager for commercial accounts.
        Filters clients on is_business boolean.
        @return: query set of commercial accounts.
        """
        return super(BusinessManager, self).get_query_set().filter(is_business='1')


class PersonalManager(models.Manager):
    def get_query_set(self):
        """
        Model manager for residential accounts.
        Filters clients on is_business boolean.
        @return: query set of residential accounts.
        """
        return super(PersonalManager, self).get_query_set().filter(is_business='0')


class Client(Person):
    client_id = models.AutoField(primary_key=True)
    client_number = models.IntegerField(max_length=10)
    business_name = models.CharField(max_length=50, blank=True)
    is_business = models.BooleanField(default=False)
    address = models.ForeignKey('common.Address', null=True, blank=True)
    contact_info = models.ForeignKey('common.Contact', null=True, blank=True)
    billing = models.ForeignKey('common.Billing_Information', null=True, blank=True)
    # managers Client.'manager'.get()
    clients = models.Manager()
    personal = PersonalManager()
    businesses = BusinessManager()

    def __unicode__(self):
        """
        Sets display for Client object to first and last name.
        @return: first and last name of Client.
        """
        if self.is_business:
            return self.business_name
        else:
            return u'%s %s' % (self.first_name, self.last_name)

    def is_a_business(self):
        """
        Checks if a client is a commercial account.
        @return: Business name or first name of the client.
        """
        if self.is_business:
            return self.business_name
        else:
            return self.first_name


class Sales_Prospect(Person):
    HIGH = 'H'
    MEDIUM = 'M'
    LOW = 'L'
    UNKNOWN = 'U'
    PROBABILITY = (
        (HIGH, 'High'),
        (MEDIUM, 'Medium'),
        (LOW, 'Low'),
        (UNKNOWN, 'Unknown'),
    )
    sales_prospect_id = models.AutoField(primary_key=True)
    liberty_contact = models.ForeignKey('employee.Employee', null=True, blank=True)
    sale_type = models.CharField(max_length=40, blank=True)
    probability = models.CharField(max_length=20, choices=PROBABILITY, blank=True)
    initial_contact_date = models.DateField(null=True, blank=True)
    comments = models.CharField(max_length=500, blank=True)
    address = models.ForeignKey('common.Address', verbose_name="prospect address", null=True, blank=True)
    contact_info = models.ForeignKey('common.Contact', verbose_name="prospect contact", null=True, blank=True)
    # 11-9 changed to is_client from if_client
    # business logic should transfer information to client if true!
    is_client = models.BooleanField(default=False)

    def __unicode__(self):
        """
        Sets display for Sales_Prospect object to first and last name.
        @return: first and last name of Sales_Prospect.
        """
        return u'%s %s' % (self.first_name, self.last_name)

liberty/client/forms.py
from django.forms import ModelForm, Textarea
from bootstrap_toolkit.widgets import BootstrapDateInput
from models import Client, Sales_Prospect

"""
Form for adding a client.
"""
class ClientForm(ModelForm):
    class Meta:
        model = Client
        exclude = ('address', 'contact_info', 'billing',)

"""
Form for adding a sales prospect.
"""
class Sales_ProspectForm(ModelForm):
    class Meta:
        model = Sales_Prospect
        exclude = ('address', 'contact_info', 'is_client',)
        widgets = {
            'initial_contact_date': BootstrapDateInput, 'termination_date': BootstrapDateInput,
            'comments': Textarea(attrs={'cols': 160, 'rows': 10})
        }

liberty/client/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from client.models import Client, Sales_Prospect
from employee.models import Employee
from common.models import Address, Contact, Billing_Information, City
from common.forms import AddressForm, ContactForm, CityForm, CityFormNotAuto, AddressFormNotAuto, AddressFormPlaces
from forms import ClientForm, Sales_ProspectForm
from common.helpermethods import create_address, create_contact, city_worker, update_address, update_contact, validation_helper
from client.helpermethods import create_client, create_sales_prospect, update_client, update_sales_prospect


def index(request):
    """
    lists all clients filtered by personal and commercial
    @param request: request with data
    @return: html page rendered with clients
    """
    client_detail = Client.clients.filter(is_business=False).order_by('last_name')
    business_client = Client.clients.filter(is_business=True).order_by('last_name')
    context = {'client_detail': client_detail, 'business_client': business_client}
    print("CD", client_detail)
    print("BD", business_client)
    return render(request, 'client/index.html', context)


def detail(request, client_id):
    """
    Detailed view of a single client
    @param request: request data
    @param client_id: client_id
    @return: rendered view with client detail
    """
    client_detail = Client.clients.get(pk=client_id)
    address_detail = Address.objects.get(pk=client_detail.address_id)
    contact_detail = Contact.objects.get(pk=client_detail.contact_info_id)
    try:
        billing_detail = Billing_Information.objects.get(pk=client_detail.billing_id)
    except Billing_Information.DoesNotExist:
        billing_detail = None
    context = {'client_detail': client_detail, 'address_detail': address_detail,
               'contact_detail': contact_detail, 'billing_detail': billing_detail}
    return render(request, 'client/detail.html', context)


def addclient(request):
    """
    View used to add a new client
    @param request: request data from form
    @return: redirect or form with validation errors
    """
    print("Add client view called")
    #forms
    if request.method == 'POST':
        form = ClientForm(request.POST)
        form1 = CityFormNotAuto(request.POST)
        form2 = AddressFormNotAuto(request.POST)
        form3 = ContactForm(request.POST)
        form_list = [form, form1, form2, form3]
        validation = validation_helper(form_list)

        if validation:
            city_f = request.POST.get('city_name')
            c = city_worker(request, city_f)
            a = create_address(request, c)
            con = create_contact(request)
            create_client(request, a, con)
            return HttpResponseRedirect('/clienttest/index/')
            # good god...just work!
    else:
        form = ClientForm()
        form1 = CityFormNotAuto()
        form2 = AddressFormNotAuto()
        form3 = ContactForm()

    return render(request, 'client/addclient.html', {'form': form, 'form1': form1, 'form2': form2, 'form3': form3})


def editclient(request, client_id):
    """
    View that allows a client object to be edited.
    @param request: request.
    @param client_id: client_id.
    @return: client index after success or form with validation errors.
    """
    print("EDITCLIENT CALLED")
    client = Client.clients.get(pk=client_id)
    address = Address.objects.get(pk=client.address_id)
    contact = Contact.objects.get(pk=client.contact_info_id)
    city = City.objects.get(pk=address.city_id)
    #TODO handle billing info
    # Data dictionaries
    client_dict = {'first_name': client.first_name, 'last_name': client.last_name,
                   'business_name': client.business_name, 'is_business': client.is_business,
                   'client_number': client.client_number
    }
    address_dict = {'address': address.address, 'address2': address.address2,
                    'state': address.state, 'zip_code': address.zip_code
    }
    contact_dict = {'phone': contact.phone, 'phone_extension': contact.phone_extension, 'cell': contact.cell,
                    'office_phone': contact.office_phone, 'office_phone_extension': contact.office_phone_extension,
                    'email': contact.email, 'website': contact.website
    }
    city_dict = {'city_name': city.city_name}

    form = ClientForm(request.POST)
    form2 = AddressFormNotAuto(request.POST)
    form3 = ContactForm(request.POST)
    form1 = CityFormNotAuto(request.POST)

    # validation vars
    form_v = form.is_valid()
    form2_v = form2.is_valid()
    form3_v = form3.is_valid()
    form1_v = form1.is_valid()

    # validation
    if form_v and form2_v and form3_v and form1_v:
        c = city_worker(request, request.POST.get('city_name'))
        a = update_address(request, address, c)
        con = update_contact(request, contact)
        client = update_client(request, client, a, con)
        return HttpResponseRedirect('/clienttest/index/')
    else:
        # display bound form
        form = ClientForm(client_dict)
        form2 = AddressFormNotAuto(address_dict)
        form3 = ContactForm(contact_dict)
        form1 = CityFormNotAuto(city_dict)
    return render(request, 'client/editclient.html', {'form': form, 'form2': form2, 'form3': form3, 'form1': form1})


def addsalesprospect(request):
    """
    Adds a sales prospect.
    @param request: request.
    @return: redirect to index or form with validation errors.
    """
    if request.method == 'POST':
        form = Sales_ProspectForm(request.POST)
        form1 = CityFormNotAuto(request.POST)
        form2 = AddressFormNotAuto(request.POST)
        form3 = ContactForm(request.POST)
        #check if address is showing
        show_address = request.POST.get('showaddress')
        print("show address value", show_address)
        f_valid = form.is_valid()
        f3_valid = form3.is_valid()
        # address is entered
        if show_address != 'None':
            # sweet validation
            f1_valid = form1.is_valid()
            f2_valid = form2.is_valid()

            print("Form validation: ", f_valid, "1:", f1_valid, "2:", f2_valid, '3:', f3_valid)

            if form.is_valid() and form1.is_valid() and form2.is_valid() and form3.is_valid():
                #city
                city_f = request.POST.get('city_name')
                c = city_worker(request, city_f)
                # address
                a = create_address(request, c)
                # contact
                con = create_contact(request)
                #sales prospect
                create_sales_prospect(address=a, contact_info=con)

                #handle success!
                return HttpResponseRedirect('/clienttest/salesprospectindex/')
        # no address entered
        if f_valid and f3_valid:
            con = create_contact(request)
            create_sales_prospect(request, con)
            return HttpResponseRedirect('/clienttest/salesprospectindex/')


    else:
        form = Sales_ProspectForm()
        form1 = CityFormNotAuto()
        form2 = AddressFormNotAuto()
        form3 = ContactForm()

    return render(request, 'client/addsalescontact.html',
                  {'form': form, 'form1': form1, 'form2': form2, 'form3': form3})


def editsalesprospect(request, sales_prospect_id):
    """
    Edits a Sales_Prospect object.
    @param request: request.
    @param sales_prospect_id: pk of object.
    @return: redirect or form with validation errors.
    """
    sp = Sales_Prospect.objects.get(pk=sales_prospect_id)
    contact = Contact.objects.get(pk=sp.contact_info_id)
    # There does not have to be an address =>
    address = None
    city = None
    try:
        address = Address.objects.get(pk=sp.address_id)
        city = City.objects.get(pk=address.city_id)
    except ObjectDoesNotExist:
        pass
    #data dictionaries
    sp_dict = {'first_name': sp.first_name, 'last_name': sp.last_name, 'liberty_contact': sp.liberty_contact_id,
               'sale_type': sp.sale_type, 'probability': sp.probability, 'initial_contact_date': sp.initial_contact_date,
               'comments': sp.comments
    }
    contact_dict = {'phone': contact.phone, 'phone_extension': contact.phone_extension, 'cell': contact.cell,
                    'office_phone': contact.office_phone, 'office_phone_extension': contact.office_phone_extension,
                    'email': contact.email, 'website': contact.website
    }

    if address is not None:
        address_dict = {'address': address.address, 'address2': address.address2,
                    'state': address.state, 'zip_code': address.zip_code
    }
    else:
        address_dict = {'address': '', 'address2': '',
                    'state': '', 'zip_code': ''}
    if city is not None:
        city_dict = {'city_name': city.city_name}
    else:
        city_dict = {'city_name': ''}
    #submitted form
    if request.method == 'POST':
        form = Sales_ProspectForm(request.POST)
        form1 = CityFormNotAuto(request.POST)
        form2 = AddressFormNotAuto(request.POST)
        form3 = ContactForm(request.POST)
        #check if address is showing
        show_address = request.POST.get('showaddress')
        print("show address value =>", show_address, show_address == None)
        f_valid = form.is_valid()
        f3_valid = form3.is_valid()
        # address is entered
        f1_valid = False
        f2_valid = False
        if show_address is not None:
            # sweet validation
            f1_valid = form1.is_valid()
            f2_valid = form2.is_valid()
        #elif show_address is not None:

        print("Form validation: ", f_valid, "1:", f1_valid, "2:", f2_valid, '3:', f3_valid)

        if f_valid and f1_valid and f2_valid and f3_valid:
            print("WITH ADDRESS")

liberty/client/templates/client/addclient.html
{% extends 'base.html' %}
{% block body_block %}
    <body onload="initialize()">
{% endblock %}
{% load bootstrap_toolkit %}
{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <div id="locationField">
        <input id="autocomplete" placeholder="Enter your address"
        onFocus="geolocate()" type="text"></input>
    </div>
    {{ form2 }}

    {{ form1 }}

    {{ form3 }}

    <div class="form-actions">
        <input type="submit" value="Submit" class="btn btn-primary" />
    </div>
</form>
{% endblock %}

liberty/client/templates/client/addsalescontact.html
{% extends 'base.html' %}
{% block body_block %}
<body onload="initialize()">
{% endblock %}
{% load bootstrap_toolkit %}

{% block content %}
{% load static %}
<script type="text/javascript" src="{{ STATIC_URL }}js/show_div_checkbox.js"></script>

    <p>Add a sales contact.</p>
    <form action="" method="post">
    {% csrf_token %}
    {{ form }}
    {% block address %}
    <!-- address is optional for sales clients -->
    <tr><th>
        <label>Select to enter contact address</label>
    </th><td>
        <input type="checkbox" name="showaddress" id="showaddress"
        onclick="fnchecked(this.checked);" value="show">
    </td></tr>
    <br />
    <div id="address" style="display:none">

    <br />
    <p>Enter sales contact address</p>
    <div id="locationField">
        <input id="autocomplete" placeholder="Enter your address"
        onFocus="geolocate()" type="text"></input>
    </div>
    {{ form2 }}

    {{ form1 }}
    </div>
    {% endblock %}
    <!-- end address -->
    <p>Contact Information:</p>
    {{ form3 }}

    <div class="form-actions">
        <input type="submit" value="Submit" class="btn btn-primary" />
    </div>
</form>
{% endblock %}

liberty/client/templates/client/detail.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}

{% block content %}

{% if client_detail or business_client %}
    <a href="{% url 'client:editclient' client_detail.client_id %}">
        Edit Client Information
    </a>
    <a href="{% url 'site_info:details' client_detail.client_id %}">
        Client Site Information
    </a>
    <ul>
        <li>
            Client Info
        </li>
        {% if client_detail %}
        <li>
            {{ client_detail.first_name }} {{ client_detail.last_name }}
        </li>
        {% endif %}
        {% if business_client %}
        <li>
            {{ business_client.business_name }}
        </li>
        <li>
            {{ business_client.first_name }} {{ business_client.last_name }}
        </li>
        {% endif %}
        <li>
            Client Address:
        </li>
        {% if address_detail %}
        <li>
            {{ address_detail }}
        </li>
        {% else %}
        <li>
            No address info.
        </li>
        {% endif %}
        <li>
            Client Contact:
        </li>
        {% if contact_detail %}
        <li>
            {{ contact_detail }}
        </li>
        {% else %}
        <li>
            No contact information
        </li>
        {% endif %}
        <li>
            Billing Information
        </li>
        {% if billing_detail %}
        <li>
            {{ billing_detail }}
        </li>
        {% else %}
        <li>
            No billing information
        </li>
        {% endif %}
    </ul>
{% else %}
        <p>No Clients are available.</p>
{% endif %}

{% endblock %}

liberty/client/templates/client/editclient.html
{% extends 'base.html' %}
{% block body_block %}
<body onload="initialize()">
{% endblock %}
{% load bootstrap_toolkit %}
{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <div id="locationField">
        <input id="autocomplete" placeholder="Enter your address"
        onFocus="geolocate()" type="text"></input>
    </div>
    {{ form2 }}

    {{ form1 }}

    {{ form3 }}

    <div class="form-actions">
        <input type="submit" value="Submit" class="btn btn-primary" />
    </div>
</form>
{% endblock %}

liberty/client/templates/client/editsalesprospect.html
{% extends 'base.html' %}
{% block body_block %}
<body onload="initialize()">
{% endblock %}
{% load bootstrap_toolkit %}
{% block content %}
{% load static %}
<script type="text/javascript" src="{{ STATIC_URL }}js/show_div_checkbox.js"></script>


    <p>Add a sales contact.</p>
    <form action="" method="post">
    {% csrf_token %}
    {{ form }}
    {% block address %}
    <!-- address is optional for sales clients -->
    <tr><th>
        <label >Select to enter contact address</label>
    </th><td>
        <input type="checkbox" name="showaddress" id="showaddress" onclick="fnchecked(this.checked);"
                value="show">
    </td></tr>
    <br />
    <div id="address" style="display:none">

    <br />
    <p>Enter sales contact address</p>
    <div id="locationField">
        <input id="autocomplete" placeholder="Enter your address"
        onFocus="geolocate()" type="text"></input>
    </div>
    {{ form2 }}

    {{ form1 }}
    </div>
    {% endblock %}
    <!-- end address -->
    {{ form3 }}

    <div class="form-actions">
        <input type="submit" value="Submit" class="btn btn-primary" />
    </div>
</form>

{% endblock %}

liberty/client/templates/client/index.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}

{% block content %}
    <p>Liberty Security Services Client List</p>
    <p>Select a client to view details</p>
    <p>Residential Clients</p>
{% if client_detail %}
    <ul>
        {% for e in client_detail %}
        <li>
            <a href="/clienttest/{{ e.client_id }}/">
                {{e.first_name}} {{e.last_name}} <!--{{e.is_a_business}}-->
            </a>
        </li>
        {% endfor %}
    </ul>
{% else %}
        <p>No clients are available.</p>
{% endif %}

<p>Business Clients</p>
{% if business_client %}
   <ul>
        {% for b in business_client %}
        <li>
            <a href="/clienttest/{{ b.client_id }}/">
              {{ b.business_name }} <!--{{e.is_a_business}}-->
            </a>
        </li>
        {% endfor %}
    </ul>
{% else %}
        <p>No clients are available.</p>
{% endif %}
{% endblock %}

liberty/client/templates/client/salesprospectdetail.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}

{% block content %}

{% if sales_prospect_detail %}
    <a href="{% url 'client:editsalesprospect' sales_prospect_detail.sales_prospect_id %}">
        Edit Prospect Information
    </a>
    <ul>
        <li>
            Sales Prospect Information Info
        </li>
        {% if sales_prospect_detail %}
        <li>
            {{ sales_prospect_detail.first_name }} {{ sales_prospect_detail.last_name }}
        </li>
        {% endif %}

        <li>
            Prospect Address:
        </li>
        {% if address_detail %}
        <li>
            {{ address_detail }}
        </li>
        {% else %}
        <li>d
            No address info.
        </li>
        {% endif %}
        <li>
            Prospect Contact:
        </li>
        {% if contact_detail %}
        <li>
            {{ contact_detail }}
        </li>
        {% else %}
        <li>
            No contact information
        </li>
        {% endif %}
        <li>
    </ul>
{% else %}
        <p>No Sales Prospects are available.</p>
{% endif %}

{% endblock %}

liberty/client/templates/client/salesprospectindex.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}

{% block content %}
    <p>Liberty Security Services Sales Prospect List</p>
    <p>Select a contact to view details</p>

{% if sales_prospect_detail %}
    <ul>
        {% for e in sales_prospect_detail %}
        <li>
            <a href="/clienttest/salesprospectdetail/{{ e.sales_prospect_id }}/">
                {{e.first_name}} {{e.last_name}}
            </a>
        </li>
        {% endfor %}
    </ul>
{% else %}
        <p>No sales prospects are available.</p>

{% endif %}
{% endblock %}